# Generated by Django 5.0.6 on 2024-06-18 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('cinemas', '0014_cinema_phone_1_cinema_phone_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AlterField(
            model_name='seance',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.cinema'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.seance'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.PositiveIntegerField(),
        ),
    ]
