# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-06-18 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_alter_seance_date"),
        ("cinemas", "0014_cinema_phone_1_cinema_phone_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seance",
            name="hall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cinemas.hall"
            ),
        ),
    ]
