# Generated by Django 5.0.6 on 2024-06-18 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_seance_hall'),
        ('movies', '0004_alter_movie_description_alter_movie_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
            preserve_default=False,
        ),
    ]
