# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-06-18 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_seance_movie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seance",
            name="tech_type",
        ),
    ]
