# Generated by Django 5.0.6 on 2024-07-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_seance_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('seance', 'row', 'seat')},
        ),
    ]
