# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-07-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0008_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
