# Generated by Django 5.0.6 on 2024-05-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailtemplate',
            options={'ordering': ['-date_created'], 'verbose_name': 'MailTemplate', 'verbose_name_plural': 'MailTemplates'},
        ),
    ]
