# Generated by Django 5.0.6 on 2024-05-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailtemplate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailtemplate',
            options={'ordering': ['date_created'], 'verbose_name': 'MailTemplate', 'verbose_name_plural': 'MailTemplates'},
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
