# Generated by Django 5.0.6 on 2024-05-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailtemplate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='file',
            field=models.FileField(null=True, upload_to='mail_templates/<function get_timestamp_path at 0x7f998be71900>'),
        ),
    ]
