# Generated by Django 5.0.6 on 2024-05-17 19:03

import src.users.managers.user_manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', src.users.managers.user_manager.CustomUserManager()),
            ],
        ),
    ]
