# Generated by Django 5.0.6 on 2024-06-06 20:41

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('інше', 'Інше'), ('київ', 'Київ'), ('харків', 'Харків'), ('одеса', 'Одеса'), ('дніпро', 'Дніпро'), ('донецьк', 'Донецьк'), ('запоріжжя', 'Запоріжжя'), ('львів', 'Львів'), ('кривий ріг', 'Кривий Ріг'), ('миколаїв', 'Миколаїв'), ('вінниця', 'Вінниця'), ('луганськ', 'Луганськ'), ('сімферополь', 'Сімферополь'), ('херсон', 'Херсон'), ('полтава', 'Полтава'), ('чернігів', 'Чернігів'), ('черкаси', 'Черкаси'), ('житомир', 'Житомир'), ('суми', 'Суми'), ('хмельницький', 'Хмельницький'), ('чернівці', 'Чернівці'), ('рівне', 'Рівне'), ('івано-франківськ', 'Івано-Франківськ'), ('тернопіль', 'Тернопіль'), ('луцьк', 'Луцьк')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='man',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
