# Generated by Django 5.0.6 on 2024-05-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.IntegerField(choices=[(0, 'Інше'), (1, 'Київ'), (2, 'Харків'), (3, 'Одеса'), (4, 'Дніпро'), (5, 'Донецьк'), (6, 'Запоріжжя'), (7, 'Львів'), (8, 'Кривий Ріг'), (9, 'Миколаїв'), (10, 'Вінниця'), (11, 'Луганськ'), (12, 'Сімферополь'), (13, 'Херсон'), (14, 'Полтава'), (15, 'Чернігів'), (16, 'Черкаси'), (17, 'Житомир'), (18, 'Суми'), (19, 'Хмельницький'), (20, 'Чернівці'), (21, 'Рівне'), (22, 'Івано-Франківськ'), (23, 'Тернопіль'), (24, 'Луцьк')], default=0, max_length=255),
        ),
    ]
