# Generated by Django 5.0.6 on 2024-05-15 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(null=True)),
                ('speed', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'db_table': 'sliders',
            },
        ),
        migrations.CreateModel(
            name='ETEndBBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10, null=True)),
                ('use_img', models.BooleanField(null=True)),
                ('img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.image')),
            ],
            options={
                'verbose_name': 'ETEndBBanner',
                'verbose_name_plural': 'ETEndBBanners',
                'db_table': 'etend_bbs',
            },
        ),
        migrations.CreateModel(
            name='News_Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True, unique=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('content', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(null=True)),
                ('promo', models.BooleanField(null=True)),
                ('video_link', models.URLField(null=True)),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.seo')),
                ('banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='np_bnr', to='core.image')),
                ('card_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='np_card', to='core.image')),
                ('cinema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemas.cinema')),
                ('gallery', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
            ],
            options={
                'verbose_name': 'News_Promo',
                'verbose_name_plural': 'News_Promos',
                'db_table': 'news_promos',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True, unique=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('content', models.TextField(null=True)),
                ('active', models.BooleanField(null=True)),
                ('can_delete', models.BooleanField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.seo')),
                ('banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_bnr', to='core.image')),
                ('gallery', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'db_table': 'pages',
            },
        ),
    ]
