# Generated by Django 5.0.6 on 2024-05-29 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_gallery_images'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etendbbanner',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.image'),
        ),
        migrations.AlterField(
            model_name='news_promo',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='np_bnr', to='core.image'),
        ),
        migrations.AlterField(
            model_name='news_promo',
            name='card_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='np_card', to='core.image'),
        ),
        migrations.AlterField(
            model_name='news_promo',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gallery'),
        ),
        migrations.AlterField(
            model_name='news_promo',
            name='seo_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='seo_img', to='core.image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_bnr', to='core.image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gallery'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='seo_img', to='core.image'),
        ),
    ]
