# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-06-06 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspromo",
            name="seo_description",
            field=models.CharField(
                max_length=160,
                validators=[django.core.validators.MinLengthValidator(50)],
            ),
        ),
        migrations.AlterField(
            model_name="newspromo",
            name="seo_title",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="page",
            name="seo_description",
            field=models.CharField(
                max_length=160,
                validators=[django.core.validators.MinLengthValidator(50)],
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="seo_title",
            field=models.CharField(max_length=60),
        ),
    ]
