# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-06-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_newspromo_seo_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="etendbbanner",
            old_name="img",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="bottomslider",
            name="speed",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (3, "3 сек"),
                    (4, "4 сек"),
                    (5, "5 сек"),
                    (6, "6 сек"),
                    (7, "7 сек"),
                    (8, "8 сек"),
                    (9, "9 сек"),
                    (10, "10 сек"),
                    (20, "20 сек"),
                    (30, "30 сек"),
                ],
                default=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="etendbbanner",
            name="use_img",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="topslider",
            name="speed",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (3, "3 сек"),
                    (4, "4 сек"),
                    (5, "5 сек"),
                    (6, "6 сек"),
                    (7, "7 сек"),
                    (8, "8 сек"),
                    (9, "9 сек"),
                    (10, "10 сек"),
                    (20, "20 сек"),
                    (30, "30 сек"),
                ],
                default=30,
                null=True,
            ),
        ),
    ]
