# Generated by Django 5.0.6 on 2024-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_img_etendbbanner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etendbbanner',
            name='color',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
