# Generated by Django 5.0.6 on 2024-05-29 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0016_alter_cinema_gallery_alter_cinema_logo_and_more'),
        ('core', '0004_alter_gallery_images'),
        ('pages', '0003_alter_etendbbanner_img_alter_news_promo_banner_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News_Promo',
            new_name='NewsPromo',
        ),
        migrations.AlterField(
            model_name='page',
            name='banner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_bnr', to='core.image'),
        ),
    ]
