# Generated by Django 5.0.6 on 2024-06-01 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_gallery_images'),
        ('pages', '0004_rename_news_promo_newspromo_alter_page_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etendbbanner',
            name='img',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.image'),
        ),
        migrations.AlterField(
            model_name='newspromo',
            name='banner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='np_bnr', to='core.image'),
        ),
        migrations.AlterField(
            model_name='newspromo',
            name='card_img',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='np_card', to='core.image'),
        ),
        migrations.AlterField(
            model_name='newspromo',
            name='gallery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.gallery'),
        ),
        migrations.AlterField(
            model_name='newspromo',
            name='seo_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='seo_img', to='core.image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='banner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='page_bnr', to='core.image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.gallery'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='seo_img', to='core.image'),
        ),
    ]
