# Generated by Django 5.0.6 on 2024-06-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_etendbbanner_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspromo',
            name='card_img',
        ),
        migrations.AddField(
            model_name='newspromo',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newspromo',
            name='content_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newspromo',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newspromo',
            name='name_uk',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_uk',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_uk',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.JSONField(),
        ),
    ]
