# Generated by Django 5.0.6 on 2024-06-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_newspromo_card_img_newspromo_content_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspromo',
            name='content',
        ),
        migrations.RemoveField(
            model_name='newspromo',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='newspromo',
            name='content_uk',
        ),
        migrations.AddField(
            model_name='newspromo',
            name='description',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='newspromo',
            name='description_ru',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='newspromo',
            name='description_uk',
            field=models.TextField(max_length=20000, null=True),
        ),
    ]
