# Generated by Django 5.0.6 on 2024-06-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_newspromo_content_remove_newspromo_content_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspromo',
            name='cinema',
        ),
    ]
