# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-06-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_alter_newspromo_active_alter_newspromo_promo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="active",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="page",
            name="can_delete",
            field=models.BooleanField(default=False),
        ),
    ]
