# Generated by Django 5.0.6 on 2024-06-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_page_active_alter_page_can_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspromo',
            options={'ordering': ['-date_created'], 'verbose_name': 'News_Promo', 'verbose_name_plural': 'News_Promos'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-date_created'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
    ]
