# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-07-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0012_tag_name_ru_tag_name_uk"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspromo",
            name="tags",
            field=models.ManyToManyField(
                null=True, related_name="tags", to="pages.tag"
            ),
        ),
    ]
