# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-07-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0013_newspromo_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspromo",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="pages.tag"),
        ),
    ]
