# Generated by Django 5.0.6 on 2024-07-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['can_delete', '-date_created'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
    ]
