# Generated by Django 5.0.6 on 2024-07-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_page_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottomslideritem',
            options={'ordering': ['id'], 'verbose_name': 'BottomSliderItem', 'verbose_name_plural': 'BottomSliderItems'},
        ),
        migrations.AlterModelOptions(
            name='topslideritem',
            options={'ordering': ['id'], 'verbose_name': 'TopSliderItem', 'verbose_name_plural': 'TopSliderItems'},
        ),
    ]
