# Generated by Django 5.0.6 on 2024-06-06 18:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=60, null=True)),
                ('seo_description', models.CharField(max_length=160, null=True, validators=[django.core.validators.MinLengthValidator(50)])),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_uk', models.CharField(max_length=100, null=True, unique=True)),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('description_uk', models.TextField(max_length=2000, null=True)),
                ('description_ru', models.TextField(max_length=2000, null=True)),
                ('terms', models.JSONField()),
                ('terms_uk', models.JSONField(null=True)),
                ('terms_ru', models.JSONField(null=True)),
                ('address', models.TextField(max_length=2000)),
                ('coordinate', models.CharField(max_length=2000)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('banner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cin_bnr', to='core.image')),
                ('gallery', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.gallery')),
                ('logo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logo', to='core.image')),
                ('seo_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='seo_img', to='core.image')),
            ],
            options={
                'verbose_name': 'Cinema',
                'verbose_name_plural': 'Cinemas',
                'db_table': 'cinemas',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=60, null=True)),
                ('seo_description', models.CharField(max_length=160, null=True, validators=[django.core.validators.MinLengthValidator(50)])),
                ('number', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('description_uk', models.TextField(max_length=2000, null=True)),
                ('description_ru', models.TextField(max_length=2000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tech', models.CharField(choices=[('3d', '3D'), ('2d', '2D'), ('imax', 'IMAX'), ('4dx.json', '4DX'), ('5d', '5D')], default='3d', max_length=25, null=True)),
                ('banner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hall_bnr', to='core.image')),
                ('cinema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemas.cinema')),
                ('gallery', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.gallery')),
                ('schema', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schema', to='core.image')),
                ('seo_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='seo_img', to='core.image')),
            ],
            options={
                'verbose_name': 'Hall',
                'verbose_name_plural': 'Halls',
                'db_table': 'halls',
                'unique_together': {('cinema', 'number')},
            },
        ),
    ]
