# Generated by Django 5.0.6 on 2024-05-23 13:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=60, null=True)),
                ('seo_description', models.CharField(max_length=160, null=True, validators=[django.core.validators.MinLengthValidator(50)])),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='cin_bnr', to='core.image')),
                ('card_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='cin_card', to='core.image')),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='logo', to='core.image')),
                ('address', models.TextField(max_length=2000, null=True)),
                ('coordinate', models.CharField(max_length=2000, null=True)),
                ('gallery', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
                ('seo_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='seo_img', to='core.image')),
            ],
            options={
                'verbose_name': 'Cinema',
                'verbose_name_plural': 'Cinemas',
                'db_table': 'cinemas',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=60, null=True)),
                ('seo_description', models.CharField(max_length=160, null=True, validators=[django.core.validators.MinLengthValidator(50)])),
                ('number', models.CharField(max_length=60)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='hall_bnr', to='core.image')),
                ('schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='schema', to='core.image')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cinema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemas.cinema')),
                ('gallery', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
                ('seo_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='seo_img', to='core.image')),
            ],
            options={
                'verbose_name': 'Hall',
                'verbose_name_plural': 'Halls',
                'db_table': 'halls',
                'unique_together': {('cinema', 'number')},
            },
        ),
    ]
