# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-06-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinemas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinema",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
