# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-06-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinemas", "0004_remove_cinema_description_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinema",
            name="description_ru",
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="cinema",
            name="description_uk",
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="cinema",
            name="name_ru",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="cinema",
            name="name_uk",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="cinema",
            name="terms_ru",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="cinema",
            name="terms_uk",
            field=models.JSONField(null=True),
        ),
    ]
