# Generated by Django 5.0.6 on 2024-05-24 09:26

import src.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0004_alter_cinema_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[src.core.utils.validate_capitalized]),
        ),
    ]
