# Generated by Django 5.0.6 on 2024-05-24 09:29

import src.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0005_alter_cinema_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(default='A', max_length=100, unique=True, validators=[src.core.utils.validate_capitalized]),
        ),
    ]
