# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-06-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinemas", "0007_alter_hall_tech"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinema",
            name="name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
