# Generated by Django 5.0.6 on 2024-05-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0007_alter_cinema_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='description_ru',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description_uk',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_ru',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_uk',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
