# Generated by Django 5.0.6 on 2024-05-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0008_cinema_description_ru_cinema_description_uk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='card_img',
        ),
    ]
