# Generated by Django 5.0.6 on 2024-06-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0008_alter_cinema_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
