# Generated by Django 5.0.6 on 2024-06-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0009_alter_cinema_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='address_ru',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='address_uk',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
