# Generated by Django 5.0.6 on 2024-06-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0010_cinema_address_ru_cinema_address_uk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='coordinate',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='description',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='description_ru',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='description_uk',
            field=models.TextField(max_length=20000, null=True),
        ),
    ]
