# Generated by Django 5.0.6 on 2024-06-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0012_alter_cinema_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='description',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='description_ru',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='description_uk',
            field=models.TextField(max_length=20000, null=True),
        ),
    ]
