# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-06-18 11:27

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinemas", "0013_alter_hall_description_alter_hall_description_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinema",
            name="phone_1",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=None, max_length=128, region=None
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cinema",
            name="phone_2",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=None, max_length=128, region=None
            ),
            preserve_default=False,
        ),
    ]
