# Generated by Django 5.0.6 on 2024-05-29 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0014_alter_cinema_banner'),
        ('core', '0004_alter_gallery_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='banner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cin_bnr', to='core.image'),
        ),
    ]
