# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-06-18 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinemas", "0014_cinema_phone_1_cinema_phone_2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hall",
            name="schema",
        ),
    ]
