# Generated by Django 5.0.6 on 2024-06-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0015_remove_hall_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='schema',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
