# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-06-21 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinemas", "0016_hall_schema"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hall",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Hall",
                "verbose_name_plural": "Halls",
            },
        ),
    ]
