# Generated by Django 5.0.6 on 2024-05-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0016_alter_cinema_gallery_alter_cinema_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinema',
            options={'ordering': ['-date_created'], 'verbose_name': 'Cinema', 'verbose_name_plural': 'Cinemas'},
        ),
        migrations.AddField(
            model_name='cinema',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
