# Generated by Django 5.0.6 on 2024-06-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0017_alter_hall_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
