# Generated by Django 5.0.6 on 2024-05-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0018_cinema_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='terms_ru',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='terms_uk',
            field=models.JSONField(null=True),
        ),
    ]
