# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-07-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinemas", "0018_cinema_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hall",
            old_name="schema",
            new_name="layout",
        ),
        migrations.AlterField(
            model_name="hall",
            name="tech",
            field=models.CharField(
                choices=[
                    ("3d", "3D"),
                    ("2d", "2D"),
                    ("imax", "IMAX"),
                    ("4dx", "4DX"),
                    ("5d", "5D"),
                ],
                max_length=25,
            ),
        ),
    ]
