# Generated by Django 5.0.6 on 2024-07-07 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0019_rename_schema_hall_layout_alter_hall_tech'),
        ('movies', '0008_tech_remove_movie_techs_movie_techs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='tech',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.tech'),
        ),
    ]
