# Generated by Django 5.0.6 on 2024-06-01 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0020_alter_cinema_banner'),
        ('core', '0004_alter_gallery_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='gallery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.gallery'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='logo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logo', to='core.image'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='seo_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='seo_img', to='core.image'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='banner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hall_bnr', to='core.image'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='gallery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.gallery'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='schema',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schema', to='core.image'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seo_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='seo_img', to='core.image'),
        ),
    ]
