# Generated by Django 5.0.6 on 2024-06-01 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0021_alter_cinema_gallery_alter_cinema_logo_and_more'),
        ('core', '0004_alter_gallery_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='seo_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='seo_img', to='core.image'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seo_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='seo_img', to='core.image'),
        ),
    ]
