# Generated by Django 5.0.6 on 2024-06-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0022_alter_cinema_seo_image_alter_hall_seo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='slug',
        ),
        migrations.AddField(
            model_name='hall',
            name='tech',
            field=models.CharField(choices=[('3d', '3D'), ('2d', '2D'), ('imax', 'IMAX'), ('4dx', '4DX'), ('5d', '5D')], default='3d', max_length=25, null=True),
        ),
    ]
