# Generated by Django 5.0.6 on 2024-05-15 17:59

import django.core.validators
import django.db.models.deletion
import src.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'db_table': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(1)])),
                ('image', models.ImageField(null=True, upload_to=src.core.utils.get_timestamp_path)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.image')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
            ],
            options={
                'verbose_name': 'GalleryItem',
                'verbose_name_plural': 'GalleryItems',
                'db_table': 'gallery_items',
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=160, validators=[django.core.validators.MinLengthValidator(50)])),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.image')),
            ],
            options={
                'verbose_name': 'Seo',
                'db_table': 'seo',
            },
        ),
    ]
