# Generated by Django 5.0.6 on 2024-05-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_remove_cinema_seo_remove_hall_seo_and_more'),
        ('core', '0001_initial'),
        ('movies', '0002_remove_movie_seo_movie_seo_description_and_more'),
        ('pages', '0002_remove_news_promo_seo_remove_page_seo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seo',
        ),
    ]
