# Generated by Django 5.0.6 on 2024-05-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_gallery_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ManyToManyField(related_query_name='images', to='core.image'),
        ),
    ]
