# Generated by Django 5.0.6 on 2024-05-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_seo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryItem',
            new_name='GalleryImage',
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'GalleryImage', 'verbose_name_plural': 'GalleryImages'},
        ),
        migrations.AlterModelTable(
            name='galleryimage',
            table='gallery_images',
        ),
    ]
