# Generated by Django 5.0.6 on 2024-05-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_gallery_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ManyToManyField(to='core.image'),
        ),
    ]
