# Generated by Django 5.0.6 on 2024-05-15 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'MovieGenre',
                'verbose_name_plural': 'MovieGenres',
                'db_table': 'movie_genres',
            },
        ),
        migrations.CreateModel(
            name='MovieParticipantPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'MovieParticipant',
                'verbose_name_plural': 'MovieParticipants',
                'db_table': 'movie_participant_persons',
            },
        ),
        migrations.CreateModel(
            name='MovieParticipantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'MovieParticipantRole',
                'verbose_name_plural': 'MovieParticipantRoles',
                'db_table': 'movie_participant_roles',
            },
        ),
        migrations.CreateModel(
            name='MovieTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'MovieTech',
                'verbose_name_plural': 'MovieTechs',
                'db_table': 'movie_techs',
            },
        ),
        migrations.CreateModel(
            name='MovieParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movieparticipantperson')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movieparticipantrole')),
            ],
            options={
                'verbose_name': 'MovieParticipant',
                'verbose_name_plural': 'MovieParticipants',
                'db_table': 'movie_participants',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=2000)),
                ('banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='movie_bnr', to='core.image')),
                ('card_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='movie_card', to='core.image')),
                ('trailer_link', models.URLField(null=True)),
                ('year', models.PositiveIntegerField(null=True)),
                ('budget', models.PositiveIntegerField(null=True)),
                ('legal_age', models.PositiveIntegerField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('released', models.DateField()),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.seo')),
                ('gallery', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gallery')),
                ('genres', models.ManyToManyField(to='movies.moviegenre')),
                ('participants', models.ManyToManyField(to='movies.movieparticipant')),
                ('techs', models.ManyToManyField(to='movies.movietech')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movies',
            },
        ),
    ]
