# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-06-06 18:26

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import src.movies.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
            ],
            options={
                "verbose_name": "MovieGenre",
                "verbose_name_plural": "MovieGenres",
                "db_table": "movie_genres",
            },
        ),
        migrations.CreateModel(
            name="MovieParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "MovieParticipant",
                "verbose_name_plural": "MovieParticipants",
                "db_table": "movie_participants",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="MovieParticipantPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=255, null=True)),
                ("fullname_uk", models.CharField(max_length=255, null=True)),
                ("fullname_ru", models.CharField(max_length=255, null=True)),
            ],
            options={
                "verbose_name": "MovieParticipant",
                "verbose_name_plural": "MovieParticipants",
                "db_table": "movie_participant_persons",
            },
        ),
        migrations.CreateModel(
            name="MovieParticipantRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, null=True)),
                ("name_uk", models.CharField(max_length=60, null=True)),
                ("name_ru", models.CharField(max_length=60, null=True)),
            ],
            options={
                "verbose_name": "MovieParticipantRole",
                "verbose_name_plural": "MovieParticipantRoles",
                "db_table": "movie_participant_roles",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seo_title", models.CharField(max_length=60, null=True)),
                (
                    "seo_description",
                    models.CharField(
                        max_length=160,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(50)],
                    ),
                ),
                ("slug", models.SlugField(null=True, unique=True)),
                ("name", models.CharField(max_length=60, unique=True)),
                ("name_uk", models.CharField(max_length=60, null=True, unique=True)),
                ("name_ru", models.CharField(max_length=60, null=True, unique=True)),
                ("description", models.TextField(max_length=2000)),
                ("description_uk", models.TextField(max_length=2000, null=True)),
                ("description_ru", models.TextField(max_length=2000, null=True)),
                ("trailer_link", models.URLField(null=True)),
                ("year", models.PositiveIntegerField(null=True)),
                ("budget", models.PositiveIntegerField(null=True)),
                (
                    "legal_age",
                    models.CharField(
                        choices=[
                            ("+0", "+0"),
                            ("+6", "+6"),
                            ("+12", "+12"),
                            ("+16", "+16"),
                            ("+18", "+18"),
                        ],
                        default="+0",
                        null=True,
                    ),
                ),
                ("duration", models.DurationField(null=True)),
                ("released", models.DateField(null=True)),
                (
                    "techs",
                    src.movies.utils.MultiSelectField(
                        choices=[
                            ("3d", "3D"),
                            ("2d", "2D"),
                            ("imax", "IMAX"),
                            ("4dx.json", "4DX"),
                            ("5d", "5D"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "genres",
                    src.movies.utils.MultiSelectField(
                        choices=[
                            ("comedy", "Комедія"),
                            ("fantasy", "Фантастика"),
                            ("horror", "Жахи"),
                            ("action", "Бойовик"),
                            ("melodramas", "Мелодрами"),
                            ("thriller", "Трилер"),
                            ("mysticism", "Містика"),
                            ("detective", "Детектив"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "countries",
                    django_countries.fields.CountryField(
                        blank=True, max_length=746, multiple=True
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "card_img",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="movie_card",
                        to="core.image",
                    ),
                ),
                (
                    "gallery",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.gallery",
                    ),
                ),
                (
                    "seo_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_query_name="seo_img",
                        to="core.image",
                    ),
                ),
                ("participants", models.ManyToManyField(to="movies.movieparticipant")),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "db_table": "movies",
                "ordering": ["-date_created"],
            },
        ),
        migrations.AddField(
            model_name="movieparticipant",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.movieparticipantperson",
            ),
        ),
        migrations.AddField(
            model_name="movieparticipant",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.movieparticipantrole",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="movieparticipant",
            unique_together={("person", "role")},
        ),
    ]
