# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-06-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="budget",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="legal_age",
            field=models.CharField(
                choices=[
                    ("+0", "+0"),
                    ("+6", "+6"),
                    ("+12", "+12"),
                    ("+16", "+16"),
                    ("+18", "+18"),
                ],
                default="+0",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="released",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="trailer_link",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.PositiveIntegerField(),
        ),
    ]
