# Generated by Django 5.0.6 on 2024-05-29 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_gallery_images'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, related_name='movie_bnr', to='core.image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='card_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, related_name='movie_card', to='core.image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='gallery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gallery'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='seo_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='seo_img', to='core.image'),
        ),
    ]
