# Generated by Django 5.0.6 on 2024-05-20 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_galleryitem_galleryimage_and_more'),
        ('movies', '0002_remove_movie_seo_movie_seo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='seo_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='seo_img', to='core.image'),
        ),
    ]
