# Generated by Django 5.0.6 on 2024-05-29 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_gallery_images'),
        ('movies', '0003_alter_movie_banner_alter_movie_card_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='banner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_bnr', to='core.image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='card_img',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_card', to='core.image'),
        ),
    ]
