# Generated by Django 5.0.6 on 2024-06-01 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_gallery_images'),
        ('movies', '0004_alter_movie_banner_alter_movie_card_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='banner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie_bnr', to='core.image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='card_img',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie_card', to='core.image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='gallery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.gallery'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='seo_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='seo_img', to='core.image'),
        ),
    ]
