# Generated by Django 5.0.6 on 2024-07-03 09:05

import src.movies.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_description_alter_movie_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='techs',
            field=src.movies.utils.MultiSelectField(choices=[('3d', '3D'), ('2d', '2D'), ('imax', 'IMAX'), ('4dx', '4DX'), ('5d', '5D')], max_length=255, null=True),
        ),
    ]
