# Generated by Django 5.0.6 on 2024-07-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_techs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='movies.movieparticipant'),
        ),
    ]
