# Generated by Django 5.0.6 on 2024-06-01 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_gallery_images'),
        ('movies', '0005_alter_movie_banner_alter_movie_card_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='seo_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='seo_img', to='core.image'),
        ),
    ]
