# Generated by Django 5.0.6 on 2024-06-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_seo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description_ru',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_uk',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='name_ru',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='name_uk',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
