# Generated by Django 5.0.6 on 2024-06-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_description_ru_movie_description_uk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='banner',
        ),
    ]
