# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-07-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0007_alter_movie_participants"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("color", models.CharField(max_length=60)),
            ],
            options={
                "verbose_name": "Tech",
                "verbose_name_plural": "Techs",
                "db_table": "techs",
            },
        ),
        migrations.RemoveField(
            model_name="movie",
            name="techs",
        ),
        migrations.AddField(
            model_name="movie",
            name="techs",
            field=models.ManyToManyField(to="movies.tech"),
        ),
    ]
