# Generated by Django 5.0.6 on 2024-07-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_tech_remove_movie_techs_movie_techs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tech',
            options={'ordering': ['id'], 'verbose_name': 'Tech', 'verbose_name_plural': 'Techs'},
        ),
    ]
