# Generated by Django 5.0.6 on 2024-06-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='legal_age',
            field=models.CharField(choices=[('+0', '+0'), ('+6', '+6'), ('+12', '+12'), ('+16', '+16'), ('+18', '+18')], default='+0', null=True),
        ),
    ]
