# Generated by Django 5.0.6 on 2024-06-02 17:54

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movie_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
    ]
