# Generated by Django 5.0.6 on 2024-06-03 10:45

import src.movies.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_remove_movie_genres_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=src.movies.utils.MultiSelectField(choices=[('1', 'Комедія'), ('2', 'Фантастика'), ('3', 'Жахи'), ('4', 'Бойовик'), ('5', 'Мелодрами'), ('6', 'Трилер'), ('7', 'Містика'), ('8', 'Детектив')], default=1, max_length=40),
        ),
    ]
