# Generated by Django 5.0.6 on 2024-06-03 15:13

import src.movies.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=src.movies.utils.MultiSelectField(choices=[('Комедія', 'comedy'), ('Фантастика', 'fantasy'), ('Жахи', 'horror'), ('Бойовик', 'action'), ('Мелодрами', 'melodramas'), ('Трилер', 'thriller'), ('Містика', 'mysticism'), ('Детектив', 'detective')], max_length=40, null=True),
        ),
    ]
