# Generated by Django 5.0.6 on 2024-06-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_alter_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieparticipantperson',
            name='fullname_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movieparticipantperson',
            name='fullname_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movieparticipantrole',
            name='name_ru',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='movieparticipantrole',
            name='name_uk',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
