# Generated by Django 5.0.6 on 2024-06-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_movieparticipantperson_fullname_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieparticipantperson',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movieparticipantrole',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
