# Generated by Django 5.0.6 on 2024-06-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_alter_movieparticipantperson_fullname_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movieparticipant',
            unique_together={('person', 'role')},
        ),
    ]
