# Generated by Django 5.0.6 on 2024-06-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_alter_movieparticipant_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieparticipant',
            options={'ordering': ['-id'], 'verbose_name': 'MovieParticipant', 'verbose_name_plural': 'MovieParticipants'},
        ),
    ]
