# Generated by Django 5.0.6 on 2024-06-04 14:31

import src.movies.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_alter_movieparticipant_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='techs',
        ),
        migrations.AddField(
            model_name='movie',
            name='techs',
            field=src.movies.utils.MultiSelectField(choices=[('3d', '3D'), ('2d', '2D'), ('imax', 'IMAX'), ('4dx', '4DX'), ('5d', '5D')], max_length=255, null=True),
        ),
    ]
