# Generated by Django 5.0.6 on 2024-06-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_delete_movietech'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-date_created'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
